
spring:
  security:
    user:
      name: admin
      password: 1234

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@buzz-book.shop:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: spring-cloud-gateway-service
