server:
  port: 8000

logging:
  level:
    root: debug

spring:
  application:
    name: spring-cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
